/*
 * author: Daniel Patterson
 *
 * Tests the SpecificationWriter, which should translate Component 
 * Specifications into Specifications that are understandable by the 3D Drawer.
 */
var should = require('should')
var fs = require('fs')
var GearSpecification = require('../interface/GearSpecification.js').GearSpecification
var SpecificationWriter = require('../interface/SpecificationWriter.js').SpecificationWriter

describe('SpecificationWriter', function() {
	var writer, gearSpec

	beforeEach(function(){
		writer = new SpecificationWriter()
		gearSpec = new GearSpecification(4, 5, 4, 3, 2, 1)
	})

	describe('#addGearSpecification', function() {
		it('should add a new GearSpecification to the writer', function() {
			writer.getGears().length.should.equal(0)
			writer.addGearSpecification(gearSpec)
			writer.getGears().length.should.equal(1)
		})
	})

	describe('#writeSpecificationToFile', function() {
		var fileContents
		var fileName = '../3dDrawer/Specification.jscad'

		function writeToFileAndGetContents(done) {			
			writer.writeSpecificationToFile()
			fs.readFile(fileName, 'utf8', function(err, data) {
				fileContents = data
				done()
			})
		}

		beforeEach(function(done) {
			writeToFileAndGetContents(done)
		})

		it('should write to the file ../3dDrawer/Specification.jscad', 
			 function() {
			fs.exists(fileName, function(exists) {
				exists.should.be.true
			})
		})

		it('should include a header explaining that the file is autogenerated',
		   function() {
		  var infoHeader = '* [GENERATED FILE]'
		  fileContents.should.contain(infoHeader)
		})

		it('should include a header to allow the file to be used as an OpenJSCAD '
		   + 'library', function() {
		  var libraryHeader = 'Specification = function() {};\n\n'
		  fileContents.should.contain(libraryHeader)
		})

		it('should contain a prefix to allow OpenJSCAD access to the array of '
			 + 'GearSpecifications', function() {
			var gearPrefix = 'Specification.gears = ['
			fileContents.should.contain(gearPrefix)
		})

		it('should contain a suffix for the array of GearSpecifications so that it '
			 + 'is well-formed OpenJSCAD', function() {
			fileContents.should.contain('];')
		})

		describe('with two GearSpecifications added', function() {
			var otherGearSpec

			beforeEach(function(done) { 
				otherGearSpec = new GearSpecification(5, 6, 7, 8, 9, 2)
				writer.addGearSpecification(gearSpec)
				writer.addGearSpecification(otherGearSpec)
				writeToFileAndGetContents(done)
			})

			it('should contain a pretty-printed JSON String for both '
				 + 'GearSpecifications in an array', function() {
				 	var array = [gearSpec, otherGearSpec]
				fileContents.should.contain(JSON.stringify(array, null, 2))
			})
		}) 
	})
})