/*
 * author: Daniel Patterson
 *
 * Tests the SpecificationWriter, which should translate Component 
 * Specifications into Specifications that are understandable by the 3D Drawer.
 */
var should = require('should')
var fs = require('fs')
var Configuration = require('../tests/TestConfiguration.js')
var SpecificationWriter = require('../interface/SpecificationWriter.js').SpecificationWriter
var PlaceableComponentTest = require('../tests/PlaceableComponentTest.js')
var PlaceableComponentGroup = require('../components/PlaceableComponentGroup.js').PlaceableComponentGroup

describe('SpecificationWriter', function() {
	var writer, component
	var specFile = Configuration.specFileTarget

	beforeEach(function(){
		writer = new SpecificationWriter(specFile)
		component = PlaceableComponentTest.createFullySpecifiedTestComponent()
	})

	describe('#addAllComponents', function() {
		it('should add new Specifications to the SpecificationWriter', function() {
			writer.getSpecifications().length.should.equal(0)
			writer.addAllComponents([component])
			writer.getSpecifications().length.should.equal(1)
		})
	})

	describe('#writeSpecificationToFile', function() {
		var fileContents

		function writeToFileAndGetContents(fileName, done) {
			if (fs.existsSync(fileName))
				fs.unlinkSync(fileName)			
			writer.writeSpecificationToFile()
			fs.readFile(fileName, 'utf8', function(err, data) { 
				fileContents = data
				done()
			})
		}

		describe('the generated Specification file', function() {
			beforeEach(function(done) {
				writeToFileAndGetContents(specFile, done)
			})

			it('should write to the file ' + specFile, function() {
				fs.exists(specFile, function(exists) {
					exists.should.be.true
				})
			})

			it('should include a header explaining that the file is autogenerated',
			   function() {
			  var infoHeader = '* [GENERATED FILE]'
			  fileContents.should.contain(infoHeader)
			})

			it('should include a header to allow the file to be used as an OpenJSCAD '
			   + 'library', function() {
			  var libraryHeader = 'Specification = function() {};\n\n'
			  fileContents.should.contain(libraryHeader)
			})

			it('should contain a prefix to allow OpenJSCAD access to the array of '
				 + 'Specifications', function() {
				var componentsPrefix = 'Specification.components = ['
				fileContents.should.contain(componentsPrefix)
			})

			it('should contain a suffix for the array of ComponentSpecifications so that it '
				 + 'is well-formed OpenJSCAD', function() {
				fileContents.should.contain('];')
			})

			describe('with two ComponentSpecifications added', function() {
				var otherComponent

				beforeEach(function(done) { 
					otherComponent = PlaceableComponentTest.createFullySpecifiedTestComponent(10, 20, 30)
					writer.addAllComponents([component, otherComponent])
					writeToFileAndGetContents(specFile,done)
				})

				it('should contain a pretty-printed JSON String for both '
					 + 'ComponentSpecifications in an array', function() {
					var array = [component.toSpecification(), 
					 	           otherComponent.toSpecification()]
					fileContents.should.contain(JSON.stringify(array, null, 2))
				})
			})					
		})
	})
})