/*
 * author: Daniel Patterson
 *
 * Tests the DrawerInterface, which should translate Component 
 * Specifications into Specifications that are understandable by the 3D Drawer.
 *
 * This version adds tests based on GearTrains and Gears
 */
var should = require('should')
var fs = require('fs')
var Configuration = require('../tests/GearTestConfiguration.js')
var GearSpecification = require('../interface/GearSpecification.js').GearSpecification
var DrawerInterface = require('../../interface/DrawerInterface.js').DrawerInterface
var GearTest = require('../tests/GearTest.js')
var GearTrainTest = require('../tests/GearTrainTest.js')

describe('DrawerInterface using Gear-related Components', function() {
	var controller, gear

	beforeEach(function(){
		controller = new DrawerInterface(Configuration)
		gear = GearTest.createFullySpecifiedTestGear()
	})

	describe('#addComponent', function() {
		it('should add a new Specification to the DrawerInterface', function() {
			controller.getComponents().length.should.equal(0)
			controller.addComponent(gear)
			controller.getComponents().length.should.equal(1)
		})
	})

	describe('#addComponentGroup', function() {
		describe('When the ComponentGroup is a GearTrain', function() {
			var train

			beforeEach(function() {
				controller = new DrawerInterface(Configuration)
				train = GearTrainTest.createTestGearTrain()
				controller.addComponentGroup(train)
			})

			describe('when a Base should be autogenerated ', function() {
				beforeEach(function() {
					controller = new DrawerInterface(Configuration)
					train = GearTrainTest.createTestGearTrain()
					train.setGenerateBaseOnWrite(true)
					controller.addComponentGroup(train)
				})
				
				it('should add one more Specification than the GearTrain has Gears',
				   function() {
					controller.getComponents().length.should.equal(train.getComponents().length + 1)
				})
			})

			describe('If the GearTrain contains overlapping Gears', function() {
				beforeEach(function() {
					controller = new DrawerInterface(Configuration)
					train = GearTrainTest.createInvalidTrainWithOverlappingGears()
				})
				
				it('should not be possible', function() {
					(function() {
						controller.addComponentGroup(train)
					}).should.throw()
				})

				describe('the error message generated', function() {
					var errorMessage, overlappingGears

					beforeEach(function() {
						overlappingGears = train.findTouchingNonAdjacentComponents()
						try {
							controller.addComponentGroup(train)
						} 
						catch(err) {
							errorMessage = err.message
						}
					})

					it('should contain a string representation of the overlapping gears',
					   function() {
						for (var i = overlappingGears.length - 1; i >= 0; i--) {
							errorMessage.should.contain(overlappingGears[i].toString())
						};
					})
				})
			})		
		})
	})

	describe('#translateTo3dDrawer', function() {
		var fileContents
		var drawerPath = '../3dDrawer/'
		var specFile = Configuration.specFileTarget
		var mainFile = Configuration.mainFileTarget
		var paramFile = Configuration.paramFilePath

		function writeToFileAndGetContents(fileName, done) {			
			controller.translateTo3dDrawer()
			fs.readFile(fileName, 'utf8', function(err, data) {
				fileContents = data
				done()
			})
		}

		describe('the generated Specification file', function() {
			beforeEach(function(done) {
				writeToFileAndGetContents(specFile, done)
			})

			describe('with two GearSpecifications added', function() {
				var otherGear

				beforeEach(function(done) { 
					otherGear = GearTest.createFullySpecifiedTestGear(10, 20, 4, 5, 6)
					controller.addComponent(gear)
					controller.addComponent(otherGear)
					writeToFileAndGetContents(specFile,done)
				})

				it('should contain a pretty-printed JSON String for both '
					 + 'GearSpecifications in an array', function() {
					var array = [gear.toSpecification(), 
					 	           otherGear.toSpecification()]
					fileContents.should.contain(JSON.stringify(array, null, 2))
				})

				describe('each with an autogenerated Spindle', function() {
					var spindle, otherSpindle

					beforeEach(function(done) { 
						controller = new DrawerInterface(Configuration)
						controller.addComponent(gear)
						controller.addComponent(otherGear)
						spindle = gear.generateSpindle()
						otherSpindle = otherGear.generateSpindle()
						controller.addComponent(spindle)
						controller.addComponent(otherSpindle)
						writeToFileAndGetContents(specFile, done)
					})

					it('should contain a pretty-printed JSON String for all Specifications '
						 + 'in an array', function() {
						var array = [gear.toSpecification(), 
						 	           otherGear.toSpecification(),
						 	           spindle.toSpecification(),
						 	           otherSpindle.toSpecification()]
						fileContents.should.contain(JSON.stringify(array, null, 2))
					})
				})
			})		
		})

		describe('with a test GearTrain added', function() {
			var train, array, arrayString

			beforeEach(function(done) {
				controller = new DrawerInterface(Configuration)
				train = GearTrainTest.createTestGearTrain()
				var gears = train.getComponents()
				array = [gears[0].toSpecification(), 
				         gears[1].toSpecification(), 
				         train.generateBase().toSpecification()]
				controller.addComponentGroup(train)
				writeToFileAndGetContents(specFile, done)
				arrayString = JSON.stringify(array, null, 2)
				arrayString = replaceIDsWithZero(arrayString)
			})

			function replaceIDsWithZero(string) {
				return string.replace(/\"id\": \d+,/g, '"id": 0,')
			}
			
			it('should contain a pretty-printed JSON String for all Specifications '
				 + 'in an array', function() {
				fileContents = replaceIDsWithZero(fileContents)
				fileContents.should.contain(arrayString)
			})
		}) 
	})
})